# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_dir_Mat <- function(M) {
    .Call(`_netclust_rowsum_dir_Mat`, M)
}

colsum_dir_Mat <- function(M) {
    .Call(`_netclust_colsum_dir_Mat`, M)
}

gamma_update_HMM_stat_dir <- function(gamma, pi, theta, network, N, K) {
    .Call(`_netclust_gamma_update_HMM_stat_dir`, gamma, pi, theta, network, N, K)
}

grad_HMM_stat_dir_oe <- function(theta, gamma, network, N, K) {
    .Call(`_netclust_grad_HMM_stat_dir_oe`, theta, gamma, network, N, K)
}

grad_HMM_stat_dir_re <- function(theta, gamma, network, N, K) {
    .Call(`_netclust_grad_HMM_stat_dir_re`, theta, gamma, network, N, K)
}

hess_HMM_stat_dir_oe <- function(theta, gamma, N, K) {
    .Call(`_netclust_hess_HMM_stat_dir_oe`, theta, gamma, N, K)
}

hess_HMM_stat_dir_re <- function(theta, gamma, N, K) {
    .Call(`_netclust_hess_HMM_stat_dir_re`, theta, gamma, N, K)
}

hess_HMM_stat_dir_oe_re <- function(theta, gamma, N, K) {
    .Call(`_netclust_hess_HMM_stat_dir_oe_re`, theta, gamma, N, K)
}

ELBO_conv_HMM_stat_dir <- function(gamma, alpha, theta, network, N, K) {
    .Call(`_netclust_ELBO_conv_HMM_stat_dir`, gamma, alpha, theta, network, N, K)
}

grad_HMM_stat_dir_oe_K1 <- function(theta, network, N) {
    .Call(`_netclust_grad_HMM_stat_dir_oe_K1`, theta, network, N)
}

grad_HMM_stat_dir_re_K1 <- function(theta, network, N) {
    .Call(`_netclust_grad_HMM_stat_dir_re_K1`, theta, network, N)
}

hess_HMM_stat_dir_oe_K1 <- function(theta, N) {
    .Call(`_netclust_hess_HMM_stat_dir_oe_K1`, theta, N)
}

hess_HMM_stat_dir_re_K1 <- function(theta, N) {
    .Call(`_netclust_hess_HMM_stat_dir_re_K1`, theta, N)
}

hess_HMM_stat_dir_oe_re_K1 <- function(theta, N) {
    .Call(`_netclust_hess_HMM_stat_dir_oe_re_K1`, theta, N)
}

ELBO_conv_HMM_stat_dir_K1 <- function(theta, network, N) {
    .Call(`_netclust_ELBO_conv_HMM_stat_dir_K1`, theta, network, N)
}

rowsum_Mat <- function(M) {
    .Call(`_netclust_rowsum_Mat`, M)
}

colsum_Mat <- function(M) {
    .Call(`_netclust_colsum_Mat`, M)
}

gamma_update_HMM_stat_undir <- function(gamma, pi, theta, network, N, K) {
    .Call(`_netclust_gamma_update_HMM_stat_undir`, gamma, pi, theta, network, N, K)
}

grad_HMM_stat_undir <- function(theta, gamma, network, N, K) {
    .Call(`_netclust_grad_HMM_stat_undir`, theta, gamma, network, N, K)
}

hess_HMM_stat_undir <- function(theta, gamma, N, K) {
    .Call(`_netclust_hess_HMM_stat_undir`, theta, gamma, N, K)
}

ELBO_conv_HMM_stat_undir <- function(gamma, pi, theta, network, N, K) {
    .Call(`_netclust_ELBO_conv_HMM_stat_undir`, gamma, pi, theta, network, N, K)
}

grad_HMM_stat_undir_K1 <- function(theta, network, N) {
    .Call(`_netclust_grad_HMM_stat_undir_K1`, theta, network, N)
}

hess_HMM_stat_undir_K1 <- function(theta, N) {
    .Call(`_netclust_hess_HMM_stat_undir_K1`, theta, N)
}

ELBO_conv_HMM_stat_undir_K1 <- function(theta, network, N) {
    .Call(`_netclust_ELBO_conv_HMM_stat_undir_K1`, theta, network, N)
}

